# Carta de Demissão
print("Nome da empresa")
Nomedaempresa= input()
print("Digite o nome do gestor")
Nomedogestor= input()
print("Digite o cargo ocupado")
Nomedocargo= input()
print("Data de inicio")
datainicio= input()
print("Data do término")
datadotérmino= input()
print("Digite o Local e a Data")
localedata= input()
print(" Digite sua assinatura")
assinatura= input()
print("Digite seu nome completo")
nomecompleto= input()

# Impressão da carta de demissão...
print(f"À {Nomedaempresa},")
print(f"Prezado (a) {Nomedogestor},")
print(f"Venho por meio desta carta comunicar formalmente o meu pedido de demissão do cargo de {Nomedocargo}")
print(f"Estarei à disposição da empresa durante o aviso prévio, no período de {datainicio} a {datadotérmino}")
print(f"{localedata}")
print(f"{assinatura}")
print(f"{nomecompleto}")